Module2 task1
htmlacademy-adaptive/1416813-cat-energy-22 pull request #2
Opened 2021-03-28 16:50 UTC by Borisova-EV

2021-03-29 06:21 UTC, Manyaka requested changes

2021-03-29 06:21 UTC, Manyaka commented on source/index.html
> +      <div class="wrapper">
лишний див

2021-03-29 06:21 UTC, Manyaka commented on source/index.html
> +        </ul>
Это - самостоятельный блок. И название класса `list` ты уже использовала. Теперь, кстати, понятно, что ты будешь на все улки вешать лист - не - это лишнее.

2021-03-29 06:21 UTC, Manyaka commented on source/index.html
> +        </dl>
самостоятельный блок

2021-03-29 06:21 UTC, Manyaka commented on source/index.html
> +      <div class="wrapper">
долой

2021-03-29 06:21 UTC, Manyaka commented on source/index.html
> +              class="slider__img slider__img--active">
```suggestion
              class="slider__img">
```

тут можно без мода (модификатора), тк картинки ничем не отличаются в зависимости от активности.

2021-03-29 06:21 UTC, Manyaka commented on source/index.html
> +            <img src="img/cat/tall-cat.jpg" width="311" height="232" alt="Кот с избыточным весом"
```suggestion
            <img src="img/cat/fat-cat.jpg" width="311" height="232" alt="Кот с избыточным весом"
```

tall - высокий

2021-03-29 06:21 UTC, Manyaka commented on source/index.html
> +      <div class="wrapper">
лишняк

2021-03-29 06:21 UTC, Manyaka commented on source/index.html
> +        <div class="contacts__content contact">
лишний див

2021-03-29 06:21 UTC, Manyaka commented on source/index.html
> +      <ul class="social__list list">
самостоятельный блок, не лист

2021-03-29 06:21 UTC, Manyaka commented on source/index.html
> +    <div class="page-footer__section social">
лишний див

2021-03-29 06:21 UTC, Manyaka commented on source/index.html
> +      <a class="copyright__link" href="https://htmlacademy.ru/intensive/adaptive"
```suggestion
      <a class="copyright__link" href="https://htmlacademy.ru/intensive/adaptive" target="_blank"
```

2021-03-29 06:21 UTC, Manyaka commented on source/index.html
> +      <a class="copyright__link" href="https://htmlacademy.ru/intensive/adaptive"
это чтобы пользователь не ушёл с нашего сайта

2021-03-29 06:21 UTC, Manyaka commented on source/index.html
> +      <a class="copyright__link copyright__link--icon" href="https://htmlacademy.ru/intensive/adaptive"
аналогично, добавь таргет

2021-03-29 06:54 UTC, Borisova-EV commented on source/index.html
> +    <div class="wrapper">
Он для центрирования

2021-03-29 07:03 UTC, Borisova-EV commented on source/index.html
> +        <div class="contacts__content contact">
В десктопной версии этот блок перенесен на карту, поэтому решила сразу обернуть

2021-03-29 07:20 UTC, Borisova-EV commented on source/index.html
> +    <div class="page-footer__section social">
В футере по макету 3 раздела, в мобильной у них нижняя рамка, хотела на .page-footer__section повесить декорирования блоков

2021-03-29 07:26 UTC, Manyaka commented on source/index.html
> +    <div class="wrapper">
так боди центрируй

2021-03-29 07:54 UTC, Borisova-EV commented on source/index.html
> +    <div class="wrapper">
там карта тянется, в общем я каждый блок центрировала отдельно

2021-03-29 07:57 UTC, Manyaka commented on source/index.html
> +    <div class="wrapper">
сори, тут не боди, а хедер

2021-03-29 08:03 UTC, Manyaka commented on source/index.html
> +        <div class="contacts__content contact">
да, так-то логично

2021-03-29 08:04 UTC, Manyaka commented on source/index.html
> +    <div class="page-footer__section social">
на ul повесь

2021-03-30 05:22 UTC, Manyaka commented on source/index.html
> +    <div class="page-footer__section social">
"на ul повесь", в смысле на ul, кроме своего класса уровня блока (`social`) добавляешь `page-footer__social` и на него уже рамку вешаешь, тк рамка это принадлежность секций футера.

2021-03-30 05:33 UTC, Manyaka requested changes

2021-03-30 05:33 UTC, Manyaka commented on source/index.html
> +            <input type="range" class="slider__range" min="1" max="3" step="1">
нужен скрытый лейбл

2021-03-30 05:33 UTC, Manyaka commented on source/index.html
> +          <p class="contact__adress">ул. Большая Конюшенная, д. 19/8 Санкт-Петербург</p>
```suggestion
          <p class="contact__address">ул. Большая Конюшенная, д. 19/8 Санкт-Петербург</p>
```

2021-03-30 20:51 UTC, Borisova-EV commented on source/index.html
> +              class="slider__img slider__img--active">
я поставила для дальнейшей реализации слайдера, повесить на него display: block например, а без display: none

2021-03-31 05:20 UTC, Manyaka commented on source/index.html
> +              class="slider__img slider__img--active">
Это называется "предварительная оптимизация". Лучше этот мод добавить именно тогда, когда ты будешь делать слайдер. Тут такая тонка грань, что тебе надо думать на будущее, при этом заранее многого не делать,  тк предварительная оптимизация - зло. Зло, потому что ты тратишь время на то, что может не пригодиться. Например, что, если ты решишь сделать слайдер на js?

2021-03-31 05:41 UTC, Manyaka requested changes

2021-03-31 05:41 UTC, Manyaka commented on source/index.html
> +          <a class="product__link link" href=""
```suggestion
          <a class="product__link" href=""
```

2021-03-31 05:41 UTC, Manyaka commented on source/index.html
> +          <a class="product__link link" href=""
не надо тут самостоятельного блока для ссылки

2021-03-31 05:41 UTC, Manyaka commented on source/index.html
> +          <a class="product__link link" href=""
```suggestion
          <a class="product__link" href=""
```

2021-03-31 05:41 UTC, Manyaka commented on source/index.html
> +          <a class="product__link link" href=""
нечего вешать из стилей на самостоятельный блок. Эта ссылка одна в своем роде, других таких нет, в отличии от кнопок и заголовков.

2021-03-31 05:41 UTC, Manyaka commented on source/index.html
> +        </li>
лишние параграфы, все стили на ли, картинки - это маркеры (или бефоре)

2021-03-31 05:41 UTC, Manyaka commented on source/index.html
> +      <div class="wrapper">
лишний див

2021-03-31 05:41 UTC, Manyaka commented on source/index.html
> +          width="320" height="362" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
```suggestion
          width="320" height="362" style="border: 0;" allowfullscreen="" loading="lazy"></iframe>
```

2021-03-31 05:41 UTC, Manyaka commented on source/index.html
> +    <ul class="social page-footer-social">
```suggestion
    <ul class="social page-footer__social">
```

2021-03-31 05:41 UTC, Manyaka commented on source/index.html
> +    <div class="page-footer__section">
лишний див, всё вешается на `а`

2021-03-31 05:47 UTC, Borisova-EV commented on source/index.html
> +      <div class="wrapper">
так там же карта, она не центрируется.

2021-03-31 05:51 UTC, Manyaka commented on source/index.html
> +      <div class="wrapper">
карта в своем диве, и потом ты же её относительно боди хотела тянуть. Она кстати, не центрируется, а занимает всю ширину.

2021-03-31 06:25 UTC, Manyaka requested changes

2021-03-31 06:25 UTC, Manyaka commented on source/index.html
> +          <p class="info-data__text">Функциональное питание содержит только полезные питательные вещества.</p>
```suggestion
        <li class="info-data__item  info-data__item--eco">Функциональное питание содержит только полезные питательные вещества.</li>
```

2021-03-31 06:47 UTC, merged