Module3 task2
htmlacademy-adaptive/1416813-cat-energy-22 pull request #6
Opened 2021-04-13 08:11 UTC by Borisova-EV

2021-04-14 07:10 UTC, Manyaka requested changes

2021-04-14 07:10 UTC, Manyaka commented on source/sass/blocks/choice.scss
> +.choice__input--radio + .choice__label::before {
```suggestion
.choice__input--radio {
  + .choice__label {
    &::before {
```

2021-04-14 07:10 UTC, Manyaka commented on source/sass/blocks/choice.scss
> +.choice__input--radio + .choice__label::before {
дальше аналогично поправить

2021-04-14 07:10 UTC, Manyaka commented on source/sass/blocks/contacts.scss
> +.contacts--grey {
```suggestion
.contacts {
  &--grey {
```

2021-04-14 07:10 UTC, Manyaka commented on source/sass/blocks/program.scss
> +.program__title.title {
так нельзя, значит что-то изначально не правильно сделала, что надо классы умножать, это надо переделать

2021-04-14 07:10 UTC, Manyaka commented on source/sass/blocks/contacts.scss
> +.contacts--grey {
также поправь еще в title.scss, я чёто сразу не заметила

2021-04-15 05:45 UTC, Borisova-EV commented on source/sass/blocks/choice.scss
> +.choice__input--radio + .choice__label::before {
**_.choice__input--checkbox:disabled+.choice__label,
      .choice__input--checkbox:disabled+.choice__label::before,
      .choice__input--checkbox:checked:disabled+.choice__label::after {
        opacity: 0.3;**
Исправила всё, кроме этого момента. Боюсь, потом сама не пойму, что написала, если сделать через вложенность. Или все-таки переписать отдельно прозрачность для каждого.
      }_

2021-04-16 16:37 UTC, merged